apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: travel-planner
resources:
  - namespace.yaml
  - serviceaccount.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
images:
  - name: travel-planner
    newName: travel-planner
    newTag: "0.1.0"
